AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL in private subnets (simplified)"

Parameters:
  VpcId:
    Type: String
    Description: VPC ID from Terraform output vpc_id

  PrivateSubnet1Id:
    Type: String
    Description: First private subnet ID

  PrivateSubnet2Id:
    Type: String
    Description: Second private subnet ID

  RdsSecurityGroupId:
    Type: String
    Description: RDS security group ID (must belong to the same VPC)

  DBName:
    Type: String
    Default: cloudprojectdb
    Description: Name of the initial database to create

  DBUsername:
    Type: String
    Default: admin
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    Description: >
      Master username (1–16 chars, letters/numbers, must start with a letter)

  DBPassword:
    Type: String
    Default: admin1234 
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: "Master password (at least 8 characters)"

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS in private subnets"
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      # Name omitted so AWS generates a unique one

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # Let AWS pick a unique identifier automatically by omitting DBInstanceIdentifier
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RdsSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 0

Outputs:
  DatabaseEndpoint:
    Description: RDS database endpoint address
    Value: !GetAtt MyDBInstance.Endpoint.Address
